#load "system.io.csx" 
#load "system.net.primitives.csx" 
#load "system.runtime.csx" 
#load "system.threading.tasks.csx" 
#r "System" 
#r "mscorlib" 
#r "../../packages/System.Net.Sockets/lib/net46/System.Net.Sockets.dll" 