#load "system.diagnostics.debug.csx" 
#load "system.diagnostics.tracing.csx" 
#load "system.resources.resourcemanager.csx" 
#load "system.runtime.csx" 
#load "system.threading.csx" 
#r "../../packages/System.Buffers/lib/netstandard1.1/System.Buffers.dll" 