# Was generated by hands

# Does here any project describetion needed?

CONFIG += c++11

DESTDIR = bin

HEADERS += include/*.h

QT += core gui
QT += widgets

SOURCES += src/*.cpp

TEMPLATE = app

OBJECTS_DIR = obj

#MOC_DIR ? Is it obj as well for moc_* files? Or src?

MOC_DIR = src

# Powered by beloved Sublime Text :)