// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Sem4Tasks")>]
[<assembly: AssemblyProductAttribute("Sem4Tasks")>]
[<assembly: AssemblyDescriptionAttribute("Tasks for semester 4")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Sem4Tasks"
    let [<Literal>] AssemblyProduct = "Sem4Tasks"
    let [<Literal>] AssemblyDescription = "Tasks for semester 4"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
